platform :ios, '11.0'

use_frameworks!
inhibit_all_warnings!

pod 'Alamofire'
pod 'SDWebImage'
pod 'R.swift'
pod 'SwiftLint'
pod 'Fabric'
pod 'Crashlytics'
pod 'JGProgressHUD'
pod 'AlamofireNetworkActivityIndicator'

target 'Visyn' do
  
end
