platform :ios, '12.0'

use_frameworks!
inhibit_all_warnings!

pod 'Alamofire'
pod 'AlamofireNetworkActivityIndicator'

pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'

pod 'R.swift'
pod 'SwiftLint'

pod 'Wormholy'

target 'App' do
  
end
